### ISSUE TITLE
Application and selection process feedback

### ISSUE THREAD

**Issue by akukas** [nodejs/mentorship#154]
There was [a comment](https://node-js.slack.com/archives/C8RND7M5Z/p1562143601094400) in #mentorship on the Node.js Slack from an applicant who was not happy with the selection process, which made me think about my own experience with the process, and the parts of it which I was annoyed by a bit.

## Summary of my involvement

On June 6, [a tweet](https://twitter.com/nodejs/status/1136646430431633409) popped up in my Explore tab. At that point, I didn't know anything about the mentorship program, but the idea sounded nice, so I decided to apply immediately. I started filling out the form, visiting the links which were included. I skimmed through the readme of this repo, and read through the mentor bios. In total, I spent about 20 minutes reading through the provided links and filling out the form. I also joined the #mentorship channel on Slack.

I listened in on the June 14 meeting, during which I realized I might have a few misconceptions about the mentorship program. This morning, July 3, I received a mail from @Bamieh informing me that I wasn't chosen for this round of membership.

Also relevant here are my expectations: I consider myself to be a mostly self-reliant person, but Node.js being the big and complex project it is, I was hoping to get matched with an experienced contributor who I could get to know and form a working relationship with, so that I can discuss ideas with them and ask for help when I run into difficult problems.

## What could be improved

Keeping in mind the extent of my involvement and any bias that might come with it, here are some of my thoughts on what could be improved.

### More indication of how selective/competitive the process is

The application form, which is where I first got all my information about the program from, didn't really communicate that only 10 applicants would end up getting matched to mentors.

The only part of the application form that sort of conveyed that message was the following, emphasis mine:

>**Are you willing to share your experience with the broader community, in what ways?**
>Sharing knowledge is the essence of the mentorship program. Sharing your experience and knowledge about mentorship will help anyone in the community and *those who did not get the opportunity to get matched this cohort*. Resources may vary from videos, blog posts, issues, or even talks and sessions!

Another part of the form conveyed the message this was a fairly relaxed program, and that there wouldn't be that many, if any, barriers to entry. I took this to refer to the application as a whole, and mean that simply applying on time is more important than writing a comprehensive application that goes into detail on your experience and motivation:

>Why are you interested in joining the program? ( *anything simple is enough* )

Finally, most of the mentor bios listed 1 to 1 as a prefered mentoring format. To me, this implied the existence of a 1 to many option, where a mentor would hold a group session with several of the multiple mentees that they selected/got assigned to them, further reinforcing my assumption that each mentor could have multiple mentees.

### Avoid fixed timelines

Looking back at the Slack channel, after applications closed, it was said that the pairs would be announced by June 20. On June 20, people were told that was actually the last day for mentors to make their picks, and that it would be at least another week before the pairs were announced.

Given that the program is still taking shape and everyone involved is volunteering their time, I find such delays perfectly reasonable. However, dates are very specific things, and people are likely to be disappointed when they are missed. Perhaps, in the future, it would be better to only provide rough estimates, such as "This next step in the process will take 2-3 weeks, we'll post updates as we have them."

---

I'd love to hear what you think about my suggestions, or if you have any other feedback of your own. As for me, I'm looking forward to making more contributions to Node (without guidance from a mentor, for the time being), and getting involved with the mentorship project in the future!

**Comment by MetaGauravSaini** [comment]
It would be helpful if the mentors mentioned the expectations from their mentees. Expectations can be like skill level - Beginner/Intermediate/etc. OR the goal that they have in mind, for example, in the Slack channel @Bamieh said _We are selecting 10 out of 100s however so that requires a lot filtering. Choosing the skill level is based on the mentor’s preference. Do they want someone experienced to help in closing issues and progressing fast, or new committers starting from the ground up_ so maybe the mentors can specify 
their preference beforehand.

**Comment by Bamieh** [comment]
@akukas  Thank you for writing this. Indeed there are many valid points here that we need to address moving forwards.

We did try to emphasize that we do not have any fixed deadlines as we are dealing with many people (mentorship team, mentors) Even as the program grows, we will still need flexible deadlines, I believe we should communicate this better in both the form and the main readme.

This program is not meant to be competitive. We do have to select a limited number of applicants, however he selection is not based on the most experienced or people with the most OSS contributions etc. Many mentees are looking for their first contribution with Node.js or OSS in general, and this is completely fine, in fact most of the selected mentees are in the category since one of the goals of this program is to bring new contributors to the Node.js ecosystem.

In the form you have to choose your top 3 mentors out of 10. Additionally in the https://github.com/nodejs/mentorship/blob/master/JOURNAL.md we do show the number of mentors for the round and rough dates. Do you think if we highlight those in the form it would be enough? Or how do you suggest we'd deliver these expectations better?

Getting feedback early on is very important to ensure a good experience for everyone applying and engaging with the program. Especially since for many mentees, mentorship is the first interaction with the Node.js Project in general. Please feel free to join us in the next mentorship meeting ( #153 ) We'd love to have you help us shape some future decisions.

**Comment by Bamieh** [comment]
@MetaGauravSaini I agree. We  should mention both  the expectations of each mentor and their time availability, this way applicants can better choose their top mentors and in turn ease the selection process from our side.

**Comment by akukas** [comment]
Yes, I understand how the program is not intended to be selective, but ends up being one due to its popularity. What was the mentor to applicant ratio in the previous cohort? How does that compare to the current one? Which way will it go in the future? Making this information known to applicants could allow them to better adjust their expectations, and including more information overall in the form itself would be a good thing.

My main issue with the readme is that it's fairly long. As mentioned in the OP, I only skimmed through it at first, which made me miss some information I would have liked to know. I'm going to try and see if I can make it more concise, or otherwise enhance its readability.

I'll try and make it to the next meeting.

**Comment by Bamieh** [comment]
@akukas You're welcome to join! We have an outstanding suggestion to work around this in the next cohort, we'll be discussing it in the next meeting.
