### ISSUE TITLE
Create a mentorship subgroup focused on to identify 6 month projects in Node.js

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#30]
During the kickoff meeting, Mentees need to identify a 6 months personal goal they want to achieve during their mentorship program, in which the mentor will be helping and guiding through.

To make things easier for mentees and open up new possibilities in the program, we need to create a subgroup responsible for identifying 6 month projects under nodeJS that the mentees could aspire to contribute to.

A few examples:
- Getting nodeJS 10 to LTS (fixing bugs, optimizations, refactors, developer experience, etc)
- Becoming a member under the community committee.
- Starting / leading an initiative

Anyone is invited to join this subgroup, especially mentors.

CC @dshaw

**Comment by mhdawson** [comment]
I'd be interested in participating.

**Comment by softwarecoder** [comment]
I'm in, I think the best example would be to develop or customize Open source learning Platform for Mentor & Mentees in next 6 months ?

**Comment by DiegoZoracKy** [comment]
@Bamieh Are the projects listed under [CommComm's Strategic Initiatives](https://github.com/nodejs/community-committee/blob/master/STRATEGIC-INITIATIVES.md) included as an option for the mentees? Do you see the mentorship program as a good opportunity to move forward some of the projects that are in a frozen or slow mode due to lack of people to work on them?

**Comment by Bamieh** [comment]
@DiegoZoracKy yes for sure! except for the projects that need a champion

**Comment by Bamieh** [comment]
closing in favor of the "priority document" #38
