### ISSUE TITLE
Set a Code of Conduct for mentors and mentees

### ISSUE THREAD

**Issue by Bamieh** [nodejs/mentorship#31]
We need to set the code of conduct for mentors and mentees to abide with and agree to. Currently we are referring to the [nodejs/admin](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md) CoC. I believe the code should be derived from the same document, but more tailored towards the mentorship program. 

Maybe already existing nodeJS members already have the needed experience to contribute in writing a draft.

CC @nodejs/coreworkinggroups @nodejs/tsc @nodejs/community-committee

**Comment by MylesBorins** [comment]
I'm personally -1 on modifying the code of conduct for this group. Perhaps extra moderation guidelines / workbooks need to be in place for handling specific edge cases.

We have adopted the [contributor covenant](https://www.contributor-covenant.org/), as document that has been collaborated on by many individuals with a ton of experience in this capacity. If it isn't sufficient we should consider working with that team upstream to expand it rather than implementing something bespoke

**Comment by gibfahn** [comment]
How about we use the existing CoC for now, and if problems arise with it we can discuss using a modified one at that point.

**Comment by dshaw** [comment]
@Bamieh The entire project uses the Node.js Code of Conduct and over the past year, we have moved from having individual copies of the document close to each project to having one central document which is housed in Admin. As @MylesBorins has already indicated, it's not going to be well received if we try to modify this before we get started.

I think the spirit of what you're asking, given the discussion at the last Mentorship team meeting, is "how can we make this easier to understand and apply?". There is generous opportunity for that and I have found some prior art:
* https://github.com/nodejs/admin/blob/master/MemberExpectations.md
* https://github.com/nodejs/admin/blob/master/Moderation-Policy.md

Both of these documents reference and build on the expectations established in the Code of Conduct. Something I think we will have to do in Mentorship. In fact, I think we can take something like Admin Member expectations and apply it almost 1-to-1 to Mentorship team members and Mentors.
