### ISSUE TITLE
task list of an education assistant and administrative assitant

### ISSUE THREAD

**Issue by nickParis11** [nodejs/mentorship#78]
https://docs.google.com/document/d/1fUpdjrcl8rRfUIGSfYsfCxoYBc9FKsErV-F3GdhXu7w/edit?usp=sharing

The document is in mode "anyone with the link can edit" mode.

**Comment by Bamieh** [comment]
Thank you so much for this nick 🥇 

I believe the education assistant is a critical separate role needed with all the points mentioned.

#### Things I am not sure about having:
- **mentor committee related things:** do we need this extra step?
- **Getting mentor’s feedback face-to-face:** mentors can join our bi-weekly meetings to reachout, they can also slack us at any time. Using google forms alone might be enough or even excessive.
- **Coordinating curriculum and keep it consistent among mentors:** I do agree with making sure that the program is consistent, however the mentorship scopes vary and no single person have the know it all across those scopes, so I would just let the mentor/mentee pair coordinate their curriculum based on the mentee's goals and the mentor's matched experiences.
- **Do live announcements:** we can do that on slack #mentorship channel, i believe it is enough.
- **Interval of follow ups:** IMO `1/10` and `1/5` are too short when applied on a 30 day scope (or even 90 days) since we cannot guarantee everyone's time plus it will become tedious.


I believe we can split the tasks of administration between the team for now, until there is a real need for it.


CC @nodejs/mentorship

**Comment by detrohutt** [comment]
Thank you Nick! This is exactly what we needed.

I agree with @Bamieh on all points he raised. I think what Nick has outlined will serve as a great "toolbox". I think initially we should implement the minimum number of tasks we *think* will be necessary for the program to run smoothly, monitor the situation, and add additional formality to the program only when pain points are identified. (No premature optimization)

It sounds like the team members have all been serving as Administrative Assistants so far and I think that is a good role for us to continue to fill, or we'd not have much to do lol.

As for consistency, I think we are enforcing a reasonable amount to start with by having mentor/mentee pairs/groups report back to their issue/pr. We can possibly try to standardize the format of their "progress reports" and design it in a way to try to identify major deviations in experience for mentees (a checklist perhaps?). We could then address those discrepancies when they come up if we feel a mentee is not getting the "full experience" we intended through our program.

I think the interval follow-ups are the most mismatched thing on this list for how our program is set up, at least for now. Since we only have a few meetings between mentor and mentee during the whole duration, I think each meeting could serve as a follow-up and we could collect data "passively" by having some communication channel open for participants to let us know what they're thinking, but not requiring that, and only *requiring* something like an end-of-program survey after all meetings, as well as describing any progress they made along the way in their progress report issue/pr.

These are just my initial thoughts, and I'm open to suggestion on any of this.
